### PR TITLE
Feature/apvs 076/income eligibility

### PR DESCRIPTION
**Pull request by tswann**
- New income eligibility partial view for Claimant Detail screen
- Dummy API endpoint to return a random income eligibility status
- Persist status to db when check runs

### CODE REVIEW

**Comment by tswann** [comment]
Hi @tmrowe - I've been experiencing some weird behaviour with the Mongo container again. This seems to work OK, but I am occasionally getting an error after the status has been updated in the db and I have to re-connect via the mongo shell to get it going again.

Can you please try this branch on your local setup before merging and see if you get similar behaviour?

**Comment by pwright08** [comment]
@tswann this runs okay for me - not seeing any errors

**Comment by tmrowe** [comment]
@tswann I'm not seeing any errors either.

**Comment by tmrowe** [comment]
So everything looks to be working well @tswann except for the redirect on clicking the button. As it stands on requesting the eligibility check it occurs and the value from the stub API is persisted to the database, but the page is not reloaded, as such the value displayed on the page stays the same until a manual page refresh.

**Comment by tswann** [comment]
@tmrowe Updated to remove the unnecessary redirect - return value will be changed by Ajax success callback.

Works on my 🎰  machine...

**Comment by tmrowe** [comment]
The HTML was referring to the status value incorrectly: 

<p id='income-status'>{{ claimant.incomeVerificationStatus }}</p>

instead of:

<p id='income-status'>{{ claimant.status.incomeVerificationStatus }}</p>

I've fixed this and will issue a pull request for the fix.

**Pull request merged**
